# This file was generated by GoReleaser. DO NOT EDIT.
cask "alicit" do
  version "1.7.0"

  on_macos do
    on_intel do
      sha256 "4c4ced0e12e4fac2fff3368b53aff90fdadd0e8e101a795d94fac75ce6a49abf"
      url "https://alicit.ai/download/v#{version}/alicit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a86bd57a755238078fd7a065dc00f363b41b205d4af67ca5e09dfdb3d3d47d0"
      url "https://alicit.ai/download/v#{version}/alicit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b60a3604cfd94af82a7150668960e1ba5ad0c34aff671fde1de0deb9cf745896"
      url "https://alicit.ai/download/v#{version}/alicit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f295f70d1fb73de29b14089baaf74ab16ebdd9a8bda9f3a1f66d913efc564c20"
      url "https://alicit.ai/download/v#{version}/alicit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "alicit"
  desc "Scoped, human-approved credentials for agents through the alicit Vault"
  homepage "https://github.com/alicit-ai/alicit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "alicit"

  # No zap stanza required

end
