# This file was generated by GoReleaser. DO NOT EDIT.
cask "alicit" do
  version "1.17.1"

  on_macos do
    on_arm do
      sha256 "ae6badbcf8bca24f3e25b54b5e927d53087fa9a66255fa0d7a891eb059aaee4e"
      url "https://alicit.ai/download/v#{version}/alicit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "481764ee92a56f3ad562f6014cf32b14bb0214a5d7634c5268b0adaada5d656c"
      url "https://alicit.ai/download/v#{version}/alicit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "adae62c26968dd2c6c3d3b66c65e954dd99230f4ce24095ad583ca5ad224c0d4"
      url "https://alicit.ai/download/v#{version}/alicit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "11821fdd21a950fd06fbda20dc19eff557f8715bb524b84ff0afb04f9f470741"
      url "https://alicit.ai/download/v#{version}/alicit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "alicit"
  desc "Scoped, human-approved credentials for agents through the alicit Vault"
  homepage "https://github.com/alicit-ai/alicit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "alicit"

  # No zap stanza required
end
