# This file was generated by GoReleaser. DO NOT EDIT.
cask "alicit" do
  version "1.8.0"

  on_macos do
    on_intel do
      sha256 "15aafe4aac3b7d1a4d3c265b8add02e522b03296336b5815e8bab9a61845bd9d"
      url "https://alicit.ai/download/v#{version}/alicit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "49bda1a4ae08c8e89ad5e7a5993f3bd5a385b79fdb47dd0fa7c6e9608dc0938c"
      url "https://alicit.ai/download/v#{version}/alicit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "351b9fcefc80d58c0f90e8e679fb199a0550037ed9a493dd7eb78c7386943de9"
      url "https://alicit.ai/download/v#{version}/alicit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9fabccf3180f69803b7798e648960791e0ac68b7bb414abb282fa1999cb30b24"
      url "https://alicit.ai/download/v#{version}/alicit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "alicit"
  desc "Scoped, human-approved credentials for agents through the alicit Vault"
  homepage "https://github.com/alicit-ai/alicit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "alicit"

  # No zap stanza required

end
